version = 1

test_patterns = ["**/*_test.go"]

exclude_patterns = ["/_example/**"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/googollee/go-socket.io"]
