all:
	go install ./base/ ./packet/ ./payload/ ./transport/...

getdev:
	go get -t ./base/ ./packet/ ./payload/ ./transport/...

test:
	go test -v -race ./base/ ./packet/ ./payload/ ./transport/...

bench:
	go test -bench . -benchmem ./base/ ./packet/ ./payload/ ./transport/...
